// AUTO-GENERATED by scripts/select-model.js. Do not edit manually.
import type { WeddingModel } from './model.types';

export const ACTIVE_MODEL: WeddingModel = {
  name: 'model-02',
  displayName: 'Model 02',
  pageModulePath: './features/model-02/pages/model-02-page/model-02-page.component',
  exportName: 'Model02PageComponent',
  supportsThemes: false,
};
