// AUTO-GENERATED by scripts/select-model.js. Do not edit manually.
import { Routes } from '@angular/router';

export const weddingPageRoute = {
  path: '',
  loadComponent: () =>
    import('./features/model-02/pages/model-02-page/model-02-page.component').then((m) => m.Model02PageComponent),
};

export const generatedRoutes: Routes = [weddingPageRoute];
