const { existsSync, mkdirSync, readFileSync, writeFileSync } = require('node:fs');
const path = require('node:path');
const { generateThemeAssets } = require('./generate-theme-assets');

const DEFAULT_THEME = 'hojas-navy';

const THEMES = {
  'hojas-navy': {
    exportName: 'TEMPLATE_HOJAS_NAVY',
    moduleName: './template-hojas-navy.theme',
  },
  'hojas-forest': {
    exportName: 'TEMPLATE_HOJAS_FOREST',
    moduleName: './template-hojas-forest.theme',
  },
};

const PALETTE_TO_CSS_VAR = {
  primary: '--theme-primary',
  primaryDark: '--theme-primary-dark',
  primarySoft: '--theme-primary-soft',
  primaryLight: '--theme-primary-light',
  coupleSeparatorText: '--theme-couple-separator-text',
  cardHeading: '--theme-card-heading',
  accent: '--theme-accent',
  heading: '--theme-heading',
  text: '--theme-text',
  surface: '--theme-surface',
  surfaceAlt: '--theme-surface-alt',
  muted: '--theme-muted',
  overlay: '--theme-overlay',
  success: '--theme-success',
  info: '--theme-info',
  border: '--theme-border',
};

function readExistingThemeName(rootDir = process.cwd()) {
  const activeThemePath = path.join(rootDir, 'src', 'app', 'features', 'shared', 'themes', 'active-theme.ts');

  if (!existsSync(activeThemePath)) {
    return undefined;
  }

  const contents = readFileSync(activeThemePath, 'utf8');
  const theme = Object.entries(THEMES).find(([, config]) => contents.includes(config.exportName));

  return theme?.[0];
}

function resolveThemeName(explicitTheme, env = process.env, rootDir = process.cwd()) {
  const themeName = explicitTheme || env.TEMPLATE_THEME || readExistingThemeName(rootDir) || DEFAULT_THEME;

  if (!THEMES[themeName]) {
    const availableThemes = Object.keys(THEMES).join(', ');
    throw new Error(`Unknown theme "${themeName}". Available themes: ${availableThemes}`);
  }

  return themeName;
}

function writeActiveThemeFile(themeName, rootDir = process.cwd()) {
  const theme = THEMES[themeName];
  const themesDir = path.join(rootDir, 'src', 'app', 'features', 'shared', 'themes');
  const activeThemePath = path.join(themesDir, 'active-theme.ts');
  const contents = [
    '// AUTO-GENERATED by scripts/select-theme.js. Do not edit manually.',
    `export { ${theme.exportName} as ACTIVE_THEME } from '${theme.moduleName}';`,
    '',
  ].join('\n');

  mkdirSync(themesDir, { recursive: true });
  writeFileSync(activeThemePath, contents);

  return activeThemePath;
}

function readPaletteFromThemeFile(themeName, rootDir = process.cwd()) {
  const theme = THEMES[themeName];
  if (!theme) {
    throw new Error(`Unknown theme "${themeName}"`);
  }

  const themeFilePath = path.join(
    rootDir,
    'src',
    'app',
    'features',
    'shared',
    'themes',
    `${theme.moduleName.replace('./', '')}.ts`
  );
  const contents = readFileSync(themeFilePath, 'utf8');
  const paletteMatch = contents.match(/palette:\s*\{([^}]+)\}/s);

  if (!paletteMatch) {
    throw new Error(`Could not parse palette from ${themeFilePath}`);
  }

  const palette = {};
  for (const [, key, value] of paletteMatch[1].matchAll(/(\w+):\s*'([^']+)'/g)) {
    palette[key] = value;
  }

  for (const key of Object.keys(PALETTE_TO_CSS_VAR)) {
    if (!palette[key]) {
      throw new Error(`Missing palette key "${key}" in ${themeFilePath}`);
    }
  }

  return palette;
}

function writeThemeVarsCss(themeName, rootDir = process.cwd()) {
  const palette = readPaletteFromThemeFile(themeName, rootDir);
  const cssVars = Object.entries(PALETTE_TO_CSS_VAR)
    .map(([key, cssVar]) => `  ${cssVar}: ${palette[key]};`)
    .join('\n');

  const contents = [
    '/* AUTO-GENERATED by scripts/select-theme.js. Do not edit manually. */',
    ':root {',
    cssVars,
    '}',
    '',
  ].join('\n');

  const outputPath = path.join(rootDir, 'src', 'theme-vars.generated.css');
  writeFileSync(outputPath, contents);
  return outputPath;
}

function updateSplashFallback(themeName, rootDir = process.cwd()) {
  const palette = readPaletteFromThemeFile(themeName, rootDir);
  const indexPath = path.join(rootDir, 'src', 'index.html');
  const html = readFileSync(indexPath, 'utf8');
  const pattern =
    /(id="app-splash"[\s\S]*?background:\s*var\(--theme-primary-soft,\s*)([^)]+)(\))/;

  if (!pattern.test(html)) {
    throw new Error('Could not find app-splash theme fallback in index.html');
  }

  const updated = html.replace(pattern, `$1${palette.primarySoft}$3`);
  writeFileSync(indexPath, updated);
  return indexPath;
}

function main(argv = process.argv.slice(2), env = process.env, rootDir = process.cwd()) {
  const themeName = resolveThemeName(argv[0], env, rootDir);
  const activeThemePath = writeActiveThemeFile(themeName, rootDir);
  const themeVarsPath = writeThemeVarsCss(themeName, rootDir);
  updateSplashFallback(themeName, rootDir);
  generateThemeAssets(themeName, rootDir);

  console.log(`Selected theme: ${themeName}`);
  console.log(`Generated: ${path.relative(rootDir, activeThemePath)}`);
  console.log(`Generated: ${path.relative(rootDir, themeVarsPath)}`);
  console.log('Generated: src\\assets\\generated\\active');
}

if (require.main === module) {
  main();
}

module.exports = {
  DEFAULT_THEME,
  THEMES,
  main,
  readExistingThemeName,
  readPaletteFromThemeFile,
  resolveThemeName,
  updateSplashFallback,
  writeActiveThemeFile,
  writeThemeVarsCss,
};
