const { existsSync, mkdirSync, readFileSync, writeFileSync } = require('node:fs');
const path = require('node:path');

const DEFAULT_MODEL = 'model-02';

const MODELS = {
  'model-02': {
    displayName: 'Model 02',
    pageModulePath: './features/model-02/pages/model-02-page/model-02-page.component',
    exportName: 'Model02PageComponent',
    supportsThemes: false,
  },
};

function readExistingModelName(rootDir = process.cwd()) {
  const activeModelPath = path.join(
    rootDir,
    'src',
    'app',
    'features',
    'shared',
    'models',
    'active-model.ts'
  );

  if (!existsSync(activeModelPath)) {
    return undefined;
  }

  const contents = readFileSync(activeModelPath, 'utf8');
  const match = contents.match(/name:\s*'(model-\d+)'/);
  return match?.[1];
}

function resolveModelName(explicitModel, env = process.env, rootDir = process.cwd()) {
  const modelName =
    explicitModel || env.TEMPLATE_MODEL || readExistingModelName(rootDir) || DEFAULT_MODEL;

  if (!MODELS[modelName]) {
    const availableModels = Object.keys(MODELS).join(', ');
    throw new Error(`Unknown model "${modelName}". Available models: ${availableModels}`);
  }

  return modelName;
}

function writeActiveModelFile(modelName, rootDir = process.cwd()) {
  const model = MODELS[modelName];
  const modelsDir = path.join(rootDir, 'src', 'app', 'features', 'shared', 'models');
  const activeModelPath = path.join(modelsDir, 'active-model.ts');
  const contents = [
    '// AUTO-GENERATED by scripts/select-model.js. Do not edit manually.',
    "import type { WeddingModel } from './model.types';",
    '',
    'export const ACTIVE_MODEL: WeddingModel = {',
    `  name: '${modelName}',`,
    `  displayName: '${model.displayName}',`,
    `  pageModulePath: '${model.pageModulePath}',`,
    `  exportName: '${model.exportName}',`,
    `  supportsThemes: ${model.supportsThemes},`,
    '};',
    '',
  ].join('\n');

  mkdirSync(modelsDir, { recursive: true });
  writeFileSync(activeModelPath, contents);

  return activeModelPath;
}

function writeAppRoutesGenerated(modelName, rootDir = process.cwd()) {
  const model = MODELS[modelName];
  const appDir = path.join(rootDir, 'src', 'app');
  const routesPath = path.join(appDir, 'app.routes.generated.ts');
  const contents = [
    '// AUTO-GENERATED by scripts/select-model.js. Do not edit manually.',
    "import { Routes } from '@angular/router';",
    '',
    'export const weddingPageRoute = {',
    "  path: '',",
    '  loadComponent: () =>',
    `    import('${model.pageModulePath}').then((m) => m.${model.exportName}),`,
    '};',
    '',
    'export const generatedRoutes: Routes = [weddingPageRoute];',
    '',
  ].join('\n');

  mkdirSync(appDir, { recursive: true });
  writeFileSync(routesPath, contents);
  return routesPath;
}

function main(argv = process.argv.slice(2), env = process.env, rootDir = process.cwd()) {
  const modelName = resolveModelName(argv[0], env, rootDir);
  const activeModelPath = writeActiveModelFile(modelName, rootDir);
  const routesPath = writeAppRoutesGenerated(modelName, rootDir);

  console.log(`Selected model: ${modelName}`);
  console.log(`Generated: ${path.relative(rootDir, activeModelPath)}`);
  console.log(`Generated: ${path.relative(rootDir, routesPath)}`);
}

if (require.main === module) {
  main();
}

module.exports = {
  DEFAULT_MODEL,
  MODELS,
  main,
  readExistingModelName,
  resolveModelName,
  writeActiveModelFile,
  writeAppRoutesGenerated,
};
